'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Resources
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("ActiveReports.Samples.SubReport.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Data Source=..\..\..\..\..\..\..\..\Data\Nwind.db.
        '''</summary>
        Friend Shared ReadOnly Property ConnectionString() As String
            Get
                Return ResourceManager.GetString("ConnectionString", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Select a Sample Report from DropDown List.
        '''</summary>
        Friend Shared ReadOnly Property ItemText1() As String
            Get
                Return ResourceManager.GetString("ItemText1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Simple SubReport.
        '''</summary>
        Friend Shared ReadOnly Property ItemText2() As String
            Get
                Return ResourceManager.GetString("ItemText2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nested SubReport.
        '''</summary>
        Friend Shared ReadOnly Property ItemText3() As String
            Get
                Return ResourceManager.GetString("ItemText3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SubReport using the data set that contains relationship.
        '''</summary>
        Friend Shared ReadOnly Property ItemText5() As String
            Get
                Return ResourceManager.GetString("ItemText5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Master-detail report containing a SubReport.
        '''</summary>
        Friend Shared ReadOnly Property ItemText6() As String
            Get
                Return ResourceManager.GetString("ItemText6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bookmark in SubReport.
        '''</summary>
        Friend Shared ReadOnly Property ItemText7() As String
            Get
                Return ResourceManager.GetString("ItemText7", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Use a parameter in the SubReport.
        '''</summary>
        Friend Shared ReadOnly Property ItemText8() As String
            Get
                Return ResourceManager.GetString("ItemText8", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to To view the DataSet with multiple tables using SubReports.
        '''</summary>
        Friend Shared ReadOnly Property ItemText9() As String
            Get
                Return ResourceManager.GetString("ItemText9", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ..\\..\\..\\rptBookmarkMain.rpx.
        '''</summary>
        Friend Shared ReadOnly Property rptBookmarkMain() As String
            Get
                Return ResourceManager.GetString("rptBookmarkMain", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ..\\..\\..\\rptBookmarkSub.rpx.
        '''</summary>
        Friend Shared ReadOnly Property rptBookmarkSub() As String
            Get
                Return ResourceManager.GetString("rptBookmarkSub", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ..\\..\\..\\rptDSRelationChildMain.rpx.
        '''</summary>
        Friend Shared ReadOnly Property rptDSRelationChildMain() As String
            Get
                Return ResourceManager.GetString("rptDSRelationChildMain", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ..\\..\\..\\rptDSRelationChildSub.rpx.
        '''</summary>
        Friend Shared ReadOnly Property rptDSRelationChildSub() As String
            Get
                Return ResourceManager.GetString("rptDSRelationChildSub", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ..\\..\\..\\rptDSRelationParent.rpx.
        '''</summary>
        Friend Shared ReadOnly Property rptDSRelationParent() As String
            Get
                Return ResourceManager.GetString("rptDSRelationParent", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ..\\..\\..\\rptMasterMain.rpx.
        '''</summary>
        Friend Shared ReadOnly Property rptMasterMain() As String
            Get
                Return ResourceManager.GetString("rptMasterMain", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ..\\..\\..\\rptMasterSub.rpx.
        '''</summary>
        Friend Shared ReadOnly Property rptMasterSub() As String
            Get
                Return ResourceManager.GetString("rptMasterSub", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ..\\..\\..\\rptNestedChildMain.rpx.
        '''</summary>
        Friend Shared ReadOnly Property rptNestedChildMain() As String
            Get
                Return ResourceManager.GetString("rptNestedChildMain", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ..\\..\\..\\rptNestedChildSub.rpx.
        '''</summary>
        Friend Shared ReadOnly Property rptNestedChildSub() As String
            Get
                Return ResourceManager.GetString("rptNestedChildSub", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ..\\..\\..\\rptNestedParent.rpx.
        '''</summary>
        Friend Shared ReadOnly Property rptNestedParent() As String
            Get
                Return ResourceManager.GetString("rptNestedParent", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ..\\..\\..\\rptParamMain.rpx.
        '''</summary>
        Friend Shared ReadOnly Property rptParamMain() As String
            Get
                Return ResourceManager.GetString("rptParamMain", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ..\\..\\..\\rptParamSub.rpx.
        '''</summary>
        Friend Shared ReadOnly Property rptParamSub() As String
            Get
                Return ResourceManager.GetString("rptParamSub", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ..\\..\\..\\rptSimpleMain.rpx.
        '''</summary>
        Friend Shared ReadOnly Property rptSimpleMain() As String
            Get
                Return ResourceManager.GetString("rptSimpleMain", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ..\\..\\..\\rptSimpleSub.rpx.
        '''</summary>
        Friend Shared ReadOnly Property rptSimpleSub() As String
            Get
                Return ResourceManager.GetString("rptSimpleSub", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ..\\..\\..\\rptUnboundDSMain.rpx.
        '''</summary>
        Friend Shared ReadOnly Property rptUnboundDSMain() As String
            Get
                Return ResourceManager.GetString("rptUnboundDSMain", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ..\\..\\..\\rptUnboundDSSub.rpx.
        '''</summary>
        Friend Shared ReadOnly Property rptUnboundDSSub() As String
            Get
                Return ResourceManager.GetString("rptUnboundDSSub", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
