//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActiveReports.Samples.BoundData.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ActiveReports.Samples.BoundData.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Source=..\..\..\..\..\..\..\..\..\Data\NWIND.DB.
        /// </summary>
        internal static string ConnectionString {
            get {
                return ResourceManager.GetString("ConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..\..\..\..\..\..\..\..\..\Data\Products_comma.csv.
        /// </summary>
        internal static string CSVDataSetPathComma {
            get {
                return ResourceManager.GetString("CSVDataSetPathComma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..\..\..\..\..\..\..\..\..\Data\Fixed_Products.csv.
        /// </summary>
        internal static string CSVDataSetPathFixed {
            get {
                return ResourceManager.GetString("CSVDataSetPathFixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..\..\..\..\..\..\..\..\..\Data\Fixed_Products_header.csv.
        /// </summary>
        internal static string CSVDataSetPathHeaderFixed {
            get {
                return ResourceManager.GetString("CSVDataSetPathHeaderFixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..\..\..\..\..\..\..\..\..\Data\Products_header_tab.csv.
        /// </summary>
        internal static string CSVDataSetPathHeaderTab {
            get {
                return ResourceManager.GetString("CSVDataSetPathHeaderTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to utf-8.
        /// </summary>
        internal static string CSVEncoding {
            get {
                return ResourceManager.GetString("CSVEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML Data (*.xml)|*.xml.
        /// </summary>
        internal static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [9],[32],[10],[10],[20],[9],[12],[12],[12],[12].
        /// </summary>
        internal static string HeaderExistsFixed {
            get {
                return ResourceManager.GetString("HeaderExistsFixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProductID[9],ProductName[32],SupplierID[10],CategoryID[10],QuantityPerUnit[20],UnitPrice[9],UnitsInStock[12],UnitsOnOrder[12],ReorderLevel[12],Discontinued[12].
        /// </summary>
        internal static string NoHeaderFixed {
            get {
                return ResourceManager.GetString("NoHeaderFixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Data File.
        /// </summary>
        internal static string OpenDataFile {
            get {
                return ResourceManager.GetString("OpenDataFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice.rpx.
        /// </summary>
        internal static string ReportName {
            get {
                return ResourceManager.GetString("ReportName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Data As.
        /// </summary>
        internal static string SaveDataAs {
            get {
                return ResourceManager.GetString("SaveDataAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a Company Name first..
        /// </summary>
        internal static string SelectCompanyName {
            get {
                return ResourceManager.GetString("SelectCompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a SQL Server first..
        /// </summary>
        internal static string SelectSQLServer {
            get {
                return ResourceManager.GetString("SelectSQLServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem retrieving SQL Server List.
        /// </summary>
        internal static string SQLServerProblem {
            get {
                return ResourceManager.GetString("SQLServerProblem", resourceCulture);
            }
        }
    }
}
